### ISSUE TITLE
Double free in validmoves

### ISSUE THREAD

**Issue by edre** [richardjs/zoe#8]
My system allocator crashes on double frees, and validmoves thusly segfaults:

```
$ make zoe_uhp
$ ./zoe_uhp
id Zoé v1.1a
ok
newgame Base
Base;NotStarted;White[1]
ok
validmoves
wA1;wB1;wG1;wS1
ok
Segmentation fault
```

It works if I use a more permissive allocator.

```
$ LD_PRELOAD=/usr/lib/libjemalloc.so.2 ./zoe_uhp
id Zoé v1.1a
ok
newgame Base
Base;NotStarted;White[1]
ok
validmoves
wA1;wB1;wG1;wS1
ok
```

I tried to run it with `CC='clang -fsanitize=address'` to pinpoint the failure, but there were too many errors building under clang.

**Comment by edre** [comment]
From ltrace, it's from the `free(args)` at the bottom of `uhp_loop()`. args gets allocated in sscanf the first time a command with an argument happens, then gets double freed the following loop with a command without an argument. Also happens with `info`.

**Comment by richardjs** [comment]
Hm, interesting. I'm having a hard time replicating. Valgrind doesn't seem to detect anything funny:

```
[richard@gliderii src]$ valgrind ./zoe_uhp
==4812== Memcheck, a memory error detector
==4812== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==4812== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==4812== Command: ./zoe_uhp
==4812== 
id Zoé v1.1a
ok
newgame Base
Base;NotStarted;White[1]
ok
validmoves
wA1;wB1;wG1;wS1
ok
exit
==4812== 
==4812== HEAP SUMMARY:
==4812==     in use at exit: 0 bytes in 0 blocks
==4812==   total heap usage: 15 allocs, 15 frees, 4,597 bytes allocated
==4812== 
==4812== All heap blocks were freed -- no leaks are possible
==4812== 
==4812== For lists of detected and suppressed errors, rerun with: -s
==4812== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

...but I'm certainly no expert on C memory allocation. Can you confirm you have the latest commits? There *was* a double-free bug earlier.

**Comment by edre** [comment]
I reproduced this on the most recent commit: df4d593. It's possible only some libc's have the sscanf behavior that leads to a double free. My patch seems simple enough and fixes it on my machine.

**Comment by richardjs** [comment]
Sorry, for some reason I hadn't seen your earlier comment and PR. I agree! Thanks!
